migManager:
  enabled: true
  repository: nvcr.io/nvidia/cloud-native
  image: k8s-mig-manager
  version: v0.8.0-ubuntu20.04
  imagePullPolicy: IfNotPresent
  imagePullSecrets: []
  env:
    - name: WITH_REBOOT
      value: "true"
  resources: {}
  config:
    name: custom-mig-parted-configs
    create: true
    data:
      config.yaml: |
        version: v1
        mig-configs:
          all-disabled:
            - devices: all
              mig-enabled: false
          custom-mig:
            - devices: [0]
              mig-enabled: false
            - devices: [1]
              mig-enabled: true
              mig-devices:
                "1g.10gb": 7
            - devices: [2]
              mig-enabled: true
              mig-devices:
                "2g.20gb": 2
                "3g.40gb": 1
            - devices: [3]
              mig-enabled: true
              mig-devices:
                "3g.40gb": 1
                "4g.40gb": 1
          custom-h100:
            - devices: [0]
              mig-enabled: true
              mig-devices:
                "1g.10gb": 7
            - devices: [1]
              mig-enabled: true
              mig-devices:
                "2g.20gb": 3
            - devices: [2]
              mig-enabled: true
              mig-devices:
                "3g.40gb": 2
            - devices: [3]
              mig-enabled: true
              mig-devices:
                "1g.20gb": 4
          custom-h200:
            - devices: [0]
              mig-enabled: true
              mig-devices:
                "1g.18gb": 7
            - devices: [1]
              mig-enabled: true
              mig-devices:
                "2g.35gb": 3
            - devices: [2]
              mig-enabled: true
              mig-devices:
                "3g.71gb": 2
            - devices: [3]
              mig-enabled: true
              mig-devices:
                "1g.35gb": 4
            - devices: [4]
              mig-enabled: true
              mig-devices:
                "4g.71gb": 1
            - devices: [5]
              mig-enabled: true
              mig-devices:
                "1g.18gb+me": 1
                "1g.18gb": 6
            - devices: [6]
              mig-enabled: true
              mig-devices:
                "7g.141gb": 1
          custom-a10040GB:
            - devices: [0]
              mig-enabled: true
              mig-devices:
                "1g.5gb": 7
            - devices: [1]
              mig-enabled: true
              mig-devices:
                "2g.10gb": 3
            - devices: [2]
              mig-enabled: true
              mig-devices:
                "1g.5gb+me": 1
                "1g.5gb": 6
            - devices: [3]
              mig-enabled: true
              mig-devices:
                "7g.40gb": 1
            - devices: [4]
              mig-enabled: true
              mig-devices:
                "3g.20gb": 2 
            - devices: [5]
              mig-enabled: true
              mig-devices:
                "4g.20gb": 1
            - devices: [6]
              mig-enabled: true
              mig-devices:
                "1g.10gb": 4

